### ISSUE TITLE
Travis only on non-trivial changes?

### ISSUE THREAD

**Issue by g2flyer** [hyperledger/fabric-private-chaincode#181]
Ursa uses travis but excludes running it for, say docu changes (see https://github.com/hyperledger/ursa/blob/master/.travis.yml).  Might be something we could also adopt?

**Comment by mbrandenburger** [comment]
With github actions you can achieve similar things. Skipping integration tests when only. `*.md` files are updated seems feasible. However, a lot of documentation also resides in `go` files. Closing this for now. Can be reopened if cycles available.
