### ISSUE TITLE
Make auction demo running with a new go-based client backend

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger/fabric-private-chaincode#332]
**Is your feature request related to a problem? Please describe.**

Extend the (~old, concept-release tagged, fabric 1.4.x-based~) auction demo with a new client backend written in go using the fabric go-client sdk.
https://github.com/hyperledger-labs/fabric-private-chaincode/tree/concept-release/demo

<--!
  Add a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
-->

**Describe the solution you'd like**
<--!
-->

**Describe alternatives you've considered**
<--!
-->

**Additional context**
<--!
-->

**Comment by MHBauer** [comment]
Existing sdk-go client programs as reference: 
 - https://github.com/MHBauer/fabric-watcher
 - https://github.com/MHBauer/fabric-query-examples
There are some examples in the sdk-go repo as well.

**Comment by MHBauer** [comment]
There doesn't seem to be a lot of implementation in https://github.com/hyperledger-labs/fabric-private-chaincode/tree/concept-release/demo/client/backend/fabric-gateway 

I see implementations calling to fabric in : 
- [getRegisteredUsers](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/concept-release/demo/client/backend/fabric-gateway/src/apiRoute.js#L14)
- [cc/invoke](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/concept-release/demo/client/backend/fabric-gateway/src/ccRoute.js#L31-L38)
- [cc/query](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/concept-release/demo/client/backend/fabric-gateway/src/ccRoute.js#L45-L52)

This last route doesn't talk to fabric.
 - [clockauctionroute staticallyserves a file](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/concept-release/demo/client/backend/fabric-gateway/src/clockauctionRoute.js#L16) 

I started by copying the server from https://github.com/hyperledger-labs/fabric-private-chaincode/tree/concept-release/demo/client/backend/mock and dumping all of the extra routes. I figure to reuse the current dependency on gin, if that is your decided router.

I'm not familiar with the config.json, but I figure maybe we can start with directly reading [the connection profile](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/concept-release/demo/client/backend/fabric-gateway/gateway/localhost/connection_profile.json).

**Comment by MHBauer** [comment]
Notes to self, 
existing gateway server is present in the auction-client-backend image, used by demo/compose.yaml
but does not appear to be currently run in the travis CI.

**Comment by g2flyer** [comment]
> existing gateway server is present in the auction-client-backend image, used by demo/compose.yaml
> but does not appear to be currently run in the travis CI.

It should indirectly via `make test` which runs the `scenario` script with `--bootstrap` which in turn should start the two docker-compose networks with core network _and_ backends!

**Comment by MHBauer** [comment]
gateway does not have a `test` target, so I don't see why it would run.

**Comment by g2flyer** [comment]
> gateway does not have a `test` target

It's not the test target in fabric-gateway but the one from ` demo/client/scripting` which pulls it in ....

**Comment by MHBauer** [comment]
@g2flyer I don't think it runs, I have a stubbed out version with no functionality, and the tests still pass. 

I doubt the tests are quite that bad, so I don't think they run.

https://github.com/MHBauer/fabric-private-chaincode/pull/1

**Comment by MHBauer** [comment]
and considering I hadn't pushed a new implementation, it definitely can't be running or isn't called.

**Comment by MHBauer** [comment]
Argh, the builds aren't linked up to the pr, but they do happen,

https://travis-ci.org/github/MHBauer/fabric-private-chaincode/builds

**Comment by MHBauer** [comment]
For now, I don't think this is going to be possible until the go-sdk gains support of wallet + gateway.

RFC:
https://github.com/hyperledger/fabric-rfcs/blob/master/text/0002-go-sdk-programming-model.md
https://hyperledger.github.io/fabric-rfcs/text/0001-chaincode-go-new-programming-model.html

JIRA for needed tasks.
https://jira.hyperledger.org/browse/FABG-928
https://jira.hyperledger.org/browse/FABG-935

We can see work going on here:
https://github.com/hyperledger/fabric-sdk-go/commits/2d73fad49fec3d4fb44f9e106fb38d38faa23b18/pkg/gateway

There seem to be some incompatibility with connection profiles that are good for node-sdk not being able to load with the go-sdk. Specifically the one in the gateway directory not loading with a basic client.

**Comment by cliveb** [comment]
@MHBauer uncertain help... https://stackoverflow.com/questions/58049430/how-to-use-c-shared-library-in-go-code-with-the-help-of-swig

**Comment by MHBauer** [comment]
https://github.com/hyperledger/fabric-samples/pull/192/ might help us get farther.

**Comment by mbrandenburger** [comment]
The auction demo is currently not compatible with the current version of FPC. We can reopen this issue once the demo will be ported to the current version.
