### ISSUE TITLE
Build-tag selectable build-time fabric system-chaincode plugin configuration

### ISSUE THREAD

**Issue by g2flyer** [hyperledger/fabric-private-chaincode#351]
Is your feature request related to a problem? Please describe.**
Currently we apply the TLCC patch to fabric which are specific to FPC and work only when building Fabric including FPC, so is unlikely to be upstreamed.   The bigger issue in Fabric though is that there is no general (build-time) way to add system-chaincode in an easy and configurable way.

**Describe the solution you'd like**
The basic idea is to use build-tags for a particular system-chaincode configuration. Practically, it would require outsourcing from `internal/peer/node/start.go` list of to-be-configured system chaincodes into a struct defined in a separate, build-tag-controlled file which then would be used inside `start.go` to iterate through (instead of the explicit list as currently done).

- [X] strategy/design on how to handle it
- [X] FPC PR #422
- [ ] [Fabric PR 1822](https://github.com/hyperledger/fabric/pull/1822)
- [ ] Adapt FPC to Fabric (once Fabric PR is integrated)

**Describe alternatives you've considered**

Carrying around a patch of a specific file. The proposed solution offers a way to replace a built in file instead of modifying it.

**Additional context**

**Comment by g2flyer** [comment]
See also [FAB-17564](https://jira.hyperledger.org/browse/FAB-17564?focusedCommentId=68563&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-68563) which touches on issue (but does not give any guidance as of 2020-05-09)

**Comment by g2flyer** [comment]
Even better approach than above might be to define a package global static variable which is used in `internal/peer/node/start.go` and then populate/extend it via `init` functions (which golang supports multiples per package and can be defined in separate build-tag controlled files).  The standard set of course could be part of the static variable initialization and on extensions might be done in separate `init` functions ....

**Comment by mbrandenburger** [comment]
FPC does not require custom system chaincode anymore. In case this integration concept comes back we can reopen this issue.
