### ISSUE TITLE
Enclave endorsement: Replace peer signature

### ISSUE THREAD

**Issue by g2flyer** [hyperledger/fabric-private-chaincode#365]
**Is your feature request related to a problem? Please describe.**
Clean(er) way of passing enclave endorsement to peer and to validate it.  This is required to implement #275.

**Describe the solution you'd like**
- as part of enclave creation, retrieve a X509 certificate on the enclave signature verification key signed by a  CA rooted in the peer's MSP. (Certificate should also include peer role attributes, maybe also additional enclave role?)
- create enclave signature in syntactic (and obviously also semantic) equivalent way to peer endorsement signature
- in endorsement plugin, replace peer endorsement signatures by enclave signature
- basic validation is now standard fabric validation. 
- Depending on whether we have public state or not, we still need a validation plugin to validate (by consulting ERCC) that the endorsement signature also comes not only from the correct peer also from an enclave registered for the particular chaincode under consideration. (This check will _always_ have to be done in TLCC ...) 

**Describe alternatives you've considered**
See #364 for "sibling" feature

**Comment by mbrandenburger** [comment]
This is not align with FPC architecture anymore.
