### ISSUE TITLE
PDO Crypto RSA pk-encryption with 3072 bit keys and unbound payload size

### ISSUE THREAD

**Issue by g2flyer** [hyperledger/fabric-private-chaincode#478]
**Is your feature request related to a problem? Please describe.**

The current pdo crypto library we use does only 2048-bit RSA for pk-encryption and also limits the message length to whatever fits into a OAEP-padded RSA encryption (~200bytes).   The former doesn't match the NIST recommendation anymore for 128-bit security and would require (at least) 3072 bits.   As request size is aproprio not bound, it would also be highly desirable to support hybrid-public-key encryption for RSA which removes the limit

**Describe the solution you'd like**
- change key size from 2048 to 3072
- either change existing EncryptMessage or add new EncryptLongMessage or alike which does hybrid encryption. (E.g., RSA-KEM as key-encapsulation algorithm and AES-256-GCM with nonce 0 as data encapsulation mechanisms; RSA-OAEP with random key and AES-256-GCM should also work and might be simpler to implement with openssl)

**Describe alternatives you've considered**
an alternative to match signatures would also be to go to EC-based crypto and DHIES. Alas, openssl _still_ does not support it, although there are some third-party packages doing it on top of openssl: 
https://github.com/chixsh/openssl-pkey-ec-ies

**Additional context**

**Comment by mbrandenburger** [comment]
@bvavala

**Comment by bvavala** [comment]
> @bvavala What does it take to bump RSA key size to 3072? Just changing a [single line in PDO](https://github.com/hyperledger-labs/private-data-objects/blob/master/common/crypto/pkenc.h#L26) - and see if it breaks FPC? [This](https://github.com/hyperledger/fabric-private-chaincode/blob/main/internal/crypto/crypto.go#L28) looks like a good candidate to fail.
> WDYT?

Possibly yes. We should try it locally, open a PR in PDO and update FPC.
I see an opportunity here for you to do your first commit in PDO :)

**Comment by mbrandenburger** [comment]
> I see an opportunity here for you to do your first commit in PDO :)

Ok, will try! :P

**Comment by mbrandenburger** [comment]
Long message asymmetric encryption was introduced with #584.

**Comment by mbrandenburger** [comment]
RSA 3072 bit keys are introduced with #605. Once #605 is merged this issue can be closed.

**Comment by mbrandenburger** [comment]
Completed with #604
