### ISSUE TITLE
Issues with Demo / Concept Release 2.0 on some hosts configurations

### ISSUE THREAD

**Issue by g2flyer** [hyperledger/fabric-private-chaincode#507]
**Describe the bug**

Assisting with somebody trying to get demo / concept-release 2.0 i noticed two potential issues which can cause build and/or run to fail:

- for whatever reason on some machines (e.g, on both my GeminiLake NUCs but not a SKL one) while running `test.sh` in `demo/chaincode/fpc`, the stringified DN gets the multi-valued OU RDN's swapped (i.e., from `OU=client+OU=org1` to `OUT=org1+OU=client`). multi-valued fields are conceptually a set but the corresponding RFC for stringifying doesn't specify an order and for some reason the go code doesn't seem to do that uniformly.  A quick-fix on a particular machine facing the problem is easy: just edit the `test.sh` and swap in the curl command on line 41 the OU's.

- the docker file is still based on sgx 2.6 which gives problems when running in HW mode with newer DCAP drivers & PSW on host as `/dev/sgx` changed from file to a directory. It should, though, still run when with using new version of SGX SDK's PSW & driver, e.g., 2.12 PSW and driver 
sgxdriver.2.11.0_4505f07.bin

**Log-filesScreenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by mbrandenburger** [comment]
Let's close this one. The current version v1.0-rc3 (#649) works with newer DCAP drivers. This issue is still useful once we port the demo from the concept-release 2.0 back to our recent version. Thanks for opening this.
