### ISSUE TITLE
transmit byte in  contract.SubmitTransaction

### ISSUE THREAD

**Issue by TrueAbc** [hyperledger/fabric-private-chaincode#551]
I want to transmit  []byte slice to chaincode using go-sdk. This is how I convert bytes to strings.
![image](https://user-images.githubusercontent.com/47651330/112751941-1fef2500-9003-11eb-91eb-76fd19cdf300.png)

And string looks like this
![image](https://user-images.githubusercontent.com/47651330/112752014-6cd2fb80-9003-11eb-8c8a-510b7facc42e.png)
Then chaincode just crashed when  contract.SubmitTransaction is invoked with string parameter above.
![image](https://user-images.githubusercontent.com/47651330/112752083-d94dfa80-9003-11eb-8407-a8d3d9bafdcc.png)

And it seems that some illegal string is passed to go runtime and make chaincode crashed.
![image](https://user-images.githubusercontent.com/47651330/112752177-49f51700-9004-11eb-8e6c-8cbf33885edd.png)

So does it mean that FPC developer need to ensure parameters safe?

**Comment by TrueAbc** [comment]
![image](https://user-images.githubusercontent.com/47651330/112752660-a22d1880-9006-11eb-95bb-41e27fb5b9c0.png)
And if I convert bytes into hexadecimal numbers, parameters are too long to encrypt.

Is there a good idea to deal with the problem?
![image](https://user-images.githubusercontent.com/47651330/112752693-d99bc500-9006-11eb-83f6-09b022fc2f03.png)

**Comment by mbrandenburger** [comment]
I suggest to use base64 encoding to send `[]byte`, this works very well. 
In go you can use `base64.StdEncoding.EncodeToString()` and inside the enclave you have a parser in `/common/base64`.

Internally we are using protocol buffers to serialise the chaincode arguments before we encrypt them. I suspect that something related to non-UTF8 characters caused your chaincode to crash. But not sure - need to dig deeper in that. 

Anyway, your enclave should not crash when submitting a "malformed" request. 
Could you please, provide more details here that I can try to reproduce the crash and see how we can fix it.

**Comment by mbrandenburger** [comment]
> And if I convert bytes into hexadecimal numbers, parameters are too long to encrypt.

How large is the data you want to send to the chaincode?

**Comment by TrueAbc** [comment]
> > And if I convert bytes into hexadecimal numbers, parameters are too long to encrypt.
> 
> How large is the data you want to send to the chaincode?

I want to send two parameters which both take 32bytes. And If I convert bytes into hexadecimal numbers like this. Every parameter takes 96 bytes.
![image](https://user-images.githubusercontent.com/47651330/112803372-c7bd2f00-90a5-11eb-8dea-70a02f3712d1.png)


Now I marshal data this way and every parameter takes 66 bytes. And it works.
![image](https://user-images.githubusercontent.com/47651330/112803851-516cfc80-90a6-11eb-82a7-9fda0d4ddcd0.png)

**Comment by TrueAbc** [comment]
> I suggest to use base64 encoding to send `[]byte`, this works very well.
> In go you can use `base64.StdEncoding.EncodeToString()` and inside the enclave you have a parser in `/common/base64`.
> 
> Internally we are using protocol buffers to serialise the chaincode arguments before we encrypt them. I suspect that something related to non-UTF8 characters caused your chaincode to crash. But not sure - need to dig deeper in that.
> 
> Anyway, your enclave should not crash when submitting a "malformed" request.
> Could you please, provide more details here that I can try to reproduce the crash and see how we can fix it.

Maybe base64 encoding is a good solution. I will try it later. 
And  I just trying to implement a  key agreement based on Elliptic Curve Cryptosystem. 

I used "ipp/ippcp.h" provided by Intel SGX in chaincode.
![image](https://user-images.githubusercontent.com/47651330/112804836-71e98680-90a7-11eb-84de-91f539b22d55.png)

As for go sdk client, I used "crypto/elliptic".  
![image](https://user-images.githubusercontent.com/47651330/112805167-d60c4a80-90a7-11eb-8c31-fb33f00cf31b.png)

And chaincode just crashed while  go client sending public key this form.
![image](https://user-images.githubusercontent.com/47651330/112751941-1fef2500-9003-11eb-91eb-76fd19cdf300.png)

**Comment by TrueAbc** [comment]
Yes, you are right. In golang, public key is in big endian form and little endian in intel sgx.  It's really time consuming to deal with it. 

Fortunately, their curve parameters are the same. For sgx_ecc256_open_context in enclave and  elliptic.P256()  in golang,they both use parameters of  prime256v1[ in this RFC doc ](https://datatracker.ietf.org/doc/rfc5114/?include_text=1)

**Comment by mbrandenburger** [comment]
> Yes, you are right. In golang, public key is in big endian form and little endian in intel sgx. It's really time consuming to deal with it.

May I ask what application you are trying to build with FPC?

**Comment by TrueAbc** [comment]
Just to implement a prototype to protect data in chaincode using enclave,  elliptic curve Diffie-Hellman, ORAM algorithm etc.  :dizzy_face:  I'm just a college student.

**Comment by mbrandenburger** [comment]
Very good!

**Comment by mbrandenburger** [comment]
> ![image](https://user-images.githubusercontent.com/47651330/112752660-a22d1880-9006-11eb-95bb-41e27fb5b9c0.png)
> And if I convert bytes into hexadecimal numbers, parameters are too long to encrypt.
> 
> Is there a good idea to deal with the problem?
> ![image](https://user-images.githubusercontent.com/47651330/112752693-d99bc500-9006-11eb-83f6-09b022fc2f03.png)

We merged PR #584 which fixed that limitation.

**Comment by mbrandenburger** [comment]
@TrueAbc I've tried to reproduce the issue related to invalid strings (See [here](https://github.com/mbrandenburger/fabric-secure-chaincode/actions/runs/863098072)) but without success. I will close this issue for now. Please do not hesitate to re-open if you still experience this issue. Thank you
