### ISSUE TITLE
Change references from labs to hyperledger

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger/fabric-private-chaincode#575]
Change references from `hyperledger-labs/fabric-private-chaincode` to `hyperledger/fabric-private-chaincode` in documentation and code.

Note that github automatically reroutes request to `hyperledger-labs/fabric-private-chaincode` to `hyperledger/fabric-private-chaincode` already. Still, documentation should be updated asap.

**Comment by mbrandenburger** [comment]
go includes must also be updated

**Comment by bvavala** [comment]
> go includes must also be updated
working on this

**Comment by mbrandenburger** [comment]
Fixed with #576
