### ISSUE TITLE
Helloworld crashes

### ISSUE THREAD

**Issue by bvavala** [hyperledger/fabric-private-chaincode#598]
`int value = std::stoi (params[1]);` raises an exception if the the conversion cannot be performed, and the exception is not captured.
As a consequence, when you send something that is not an integer/number, the helloworld chaincode crashes.

**Comment by mbrandenburger** [comment]
@bvavala would it make sense to catch all exceptions within invoke already in [enclave.cpp](https://github.com/hyperledger/fabric-private-chaincode/blob/main/ecc_enclave/enclave/enclave.cpp#L118), so we prevent the enclave from crashing in any case?

The user logic implemented inside invoke could still catch exceptions and handle accordingly?!

**Comment by bvavala** [comment]
> @bvavala would it make sense to catch all exceptions within invoke already in [enclave.cpp](https://github.com/hyperledger/fabric-private-chaincode/blob/main/ecc_enclave/enclave/enclave.cpp#L118), so we prevent the enclave from crashing in any case?
> 
> The user logic implemented inside invoke could still catch exceptions and handle accordingly?!

Yes, it's a good idea. Clearly we don't prevent crashes in general, but at least those due to unhandled exceptions.

**Comment by mbrandenburger** [comment]
Solved with #625
