### ISSUE TITLE
Sample Test-network build fails on ecc docker build

### ISSUE THREAD

**Issue by munapower** [hyperledger/fabric-private-chaincode#603]
**Describe the bug**

In a vanilla installation when you want to run the test-network sample the readme says to run make build from the test-network directory. That make build never completes. It gets stuck when it builds the ecc docker container.
**To Reproduce**

1. Go to utils/docker and execute make run
2. from FPC_ROOT_DIRECTORY run make build
3. go to samples/deployment/test-network and execute first step in readme which exports 2 environment variables and executes make build
4. Build process starts and gets stuck at "docker  build --no-cache --build-arg FPC_VERSION=main  --build-arg CAAS_PORT=9999 --build-arg CC_NAME="ecc" --build-arg CC_PATH="/usr/local/bin" --build-arg CC_LIB_PATH="/usr/local/bin/enclave/lib" -t hyperledger/fabric-private-chaincode-boilerplate-ecc -f Dockerfile.boilerplate-ecc"
**Expected behavior**

make build should complete successfully
**Log-filesScreenshots**

**Environment (please complete the following information):**

OS: Ubuntu 20.04
FPC Version: main branch
**Additional context**

**Comment by mbrandenburger** [comment]
Does it help when you run in step 3) the following:

```
cd $FPC_PATH/samples/deployment/test-network
export TEST_CC_ID=echo
export TEST_CC_PATH=${FPC_PATH}/samples/chaincode/echo
make -C $FPC_PATH/utils/docker build
make build
```

**Comment by munapower** [comment]
Tried it with:
`DOCKER_BUILDKIT=1
DOCKER_BUILD_OPTS=--no-cache` enabled and not and it worked when they are enabled ... if not, nope, it gets stuck in the ecc build of the `make -C $FPC_PATH/utils/docker build`

**Comment by munapower** [comment]
I added a --no-cache in the makefile in utils/docker and it was able to pass that, but then it got stuck again in 
`go  build  -o ecc main.go
ln -sfn ../../../ecc_enclave/_build/lib chaincode/enclave/ecc-enclave-lib
ln -sfn ../../../ecc_enclave/_build/include chaincode/enclave/ecc-enclave-include
go  test  -v ./...
?   	github.com/hyperledger/fabric-private-chaincode/ecc	[no test files]
?   	github.com/hyperledger/fabric-private-chaincode/ecc/chaincode	[no test files]
?   	github.com/hyperledger/fabric-private-chaincode/ecc/chaincode/enclave	[no test files]
?   	github.com/hyperledger/fabric-private-chaincode/ecc/chaincode/ercc	[no test files]
DOCKER_BUILDKIT=1 docker  build --no-cache --build-arg FPC_VERSION=main -t hyperledger/fabric-private-chaincode-boilerplate-ecc -f Dockerfile.boilerplate-ecc\
	--build-arg SGX_MODE=SIM\
	--build-arg CAAS_PORT=9999\
	..
[+] Building 64.1s (1/2)                                                                                                                                                       
 => [internal] load build definition from Dockerfile.boilerplate-ecc                                                                                                      0.1s
 => => transferring dockerfile: 1.27kB                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                        64.0s
 => => transferring context: 33B`

**Comment by munapower** [comment]
@mbrandenburger after updating docker, restarting, executing docker system prune --force, and going starting the fpc environment I get the following error:
`root@docker-desktop:/project/src/github.com/hyperledger/fabric-private-chaincode# cd $FPC_PATH/samples/deployment/test-network
root@docker-desktop:/project/src/github.com/hyperledger/fabric-private-chaincode/samples/deployment/test-network# export TEST_CC_ID=echo
root@docker-desktop:/project/src/github.com/hyperledger/fabric-private-chaincode/samples/deployment/test-network# export TEST_CC_PATH=${FPC_PATH}/samples/chaincode/echo
root@docker-desktop:/project/src/github.com/hyperledger/fabric-private-chaincode/samples/deployment/test-network# make -C $FPC_PATH/utils/docker build
make: Entering directory '/project/src/github.com/hyperledger/fabric-private-chaincode/utils/docker'
DOCKER_BUILDKIT=1 docker  build  --build-arg FPC_VERSION=main  -t hyperledger/fabric-private-chaincode-base-rt base-rt
failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /Users/mmunaro/.docker/run/docker.sock: connect: no such file or directory
make: *** [Makefile:175: base-rt] Error 1
make: Leaving directory '/project/src/github.com/hyperledger/fabric-private-chaincode/utils/docker'
root@docker-desktop:/project/src/github.com/hyperledger/fabric-private-chaincode/samples/deployment/test-network# `

**Comment by munapower** [comment]
New docker version has Docker Compose v2 as an experimental feature. I turned it on and it didn't give me the docker.sock error any more.
![image](https://user-images.githubusercontent.com/21000331/124018557-5bacd880-d9be-11eb-958e-87b01af8999e.png)
but now I am stuck in the build

**Comment by mbrandenburger** [comment]
> but now I am stuck in the build
Do you mean suck at the same point as before?

**Comment by munapower** [comment]
No, sorry, should have said where. `make -C $FPC_PATH/utils/docker build
make: Entering directory '/project/src/github.com/hyperledger/fabric-private-chaincode/utils/docker'
DOCKER_BUILDKIT=1 docker  build  --build-arg FPC_VERSION=main  -t hyperledger/fabric-private-chaincode-base-rt base-rt`
