### ISSUE TITLE
Improve test-network sample to accept any chaincode

### ISSUE THREAD

**Issue by munapower** [hyperledger/fabric-private-chaincode#605]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

The current test-network sample only accepts the echo chaincode. It could explain how to also use the helloworld chaincode or any other chaincode. To be able to do so the user would have to be able to configure the chaincode name and the path to the code itself.
**Describe alternatives you've considered**

The solution could be done in 2 steps. 
1. Standardize the use of CC_ID because in some parts TEST_CC_ID is used, add CC_PATH as configurable, update the Readme to reflect this change. 
2. Update just the readmes of the test-network and the helloworld samples to reflect the steps needed to use the helloworld chaincode in the test-network.
**Additional context**

**Comment by mbrandenburger** [comment]
This is a good idea Maria! Making the test-network more flexible will give developers a vehicle to easily test their FPC chaincode. Key part of this change will be `CC_ID` and `CC_PATH` as you already pointed out!

Looking forward to review your PRs on that! :)
