### ISSUE TITLE
Extended Language Support for Fabric Private Chaincode

### ISSUE THREAD

**Issue by ricc-zappoli** [hyperledger/fabric-private-chaincode#632]
**Is your feature request related to a problem? Please describe.**

Currently, writing and compiling chaincodes in FPC is only possible using C++ language. Since it is possible to have standard Fabric chaincodes written in Go, it would be great to have this possibility in FPC as well.

**Describe the solution you'd like**

As part of my master thesis project, supervised by [Christian Cachin](https://github.com/cca88) within the [Swiss Joint Master of Science in Computer Science](https://mcs.unibnf.ch/), I will work on enabling Golang chaincode support for FPC.

**Describe alternatives you've considered**

TBD

**Additional context**

Contact me at <riccardo.zappoli@unifr.ch>.

**Comment by mbrandenburger** [comment]
This is a great project! I endorse and happy to mentor this project!

**Comment by mbrandenburger** [comment]
Some interesting pointers are already collected in #279.

**Comment by mbrandenburger** [comment]
Ongoing prototype development is available at [Riccardo's fork](https://github.com/ricc-zappoli/fabric-private-chaincode/tree/golang-support).

**Comment by mbrandenburger** [comment]
closed with #698
