### ISSUE TITLE
Deleted protos under internal/protos

### ISSUE THREAD

**Issue by bvavala** [hyperledger/fabric-private-chaincode#638]
`make clean` deletes protos needed under internal/protos. A subsequent `make` then fails.

**Comment by mbrandenburger** [comment]
The generated go proto files in `internal/protos` are all checked-in in git since they are needed to make sure the client sdk can be used as a proper go dependency elsewhere. Are you saying that after `make clean`, a subsequent `make` does not trigger the recreation of the go protos?

**Comment by mbrandenburger** [comment]
Just double checked, go protos are generated again after removing them with `make clean`. Can you provide more information to re-create this issue?

**Comment by bvavala** [comment]
Right, a bit more info is needed:
the problem arises when you do a `make clean` and then try to build `common`. This is because the Go attestation conversion depends on `protos`, which is not rebuilt at that point -- i.e., inside `common`. Hence, `common` is not self-contained.

Possible solutions: remove that dependency, or move `protos` in `common`.

Anyway, closing this for now, as it is not an issue at the top level of the repo.
