### ISSUE TITLE
Failed to generate a Dockerfile: Unknown chaincodeType: EXTERNAL

### ISSUE THREAD

**Issue by Ren-HK** [hyperledger/fabric-private-chaincode#658]
when Install ERCC and ECC, I get a error:
```bash
Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: platform builder failed: Failed to generate a Dockerfile: Unknown chaincodeType: EXTERNAL
```
it caused by `installFPC.sh`
```bash
# Install ERCC and ECC
#---------------------
echo ""
echo "Installing chaincodes"

# as Org 1
setGlobals 1
peer lifecycle chaincode install $PKG_PATH/${ERCC_ID}.${PEERS[0]}.tgz
peer lifecycle chaincode install $PKG_PATH/${CC_ID}.${PEERS[0]}.tgz
```
How to solve this~

**Comment by bvavala** [comment]
Please check a couple of solutions outlined [here](https://stackoverflow.com/questions/61405242/hyperledger-fabric-2-0-chaincode-as-external-serviceunknown-chaincodetype-ext). It may be due to some local misconfiguration.

**Comment by mbrandenburger** [comment]
@Ren-HK Did you try to follow the [FPC test network tutorial](https://github.com/hyperledger/fabric-private-chaincode/tree/main/samples/deployment/test-network) when this problem occurred?

**Comment by mbrandenburger** [comment]
I propose to close this issue due to inactivity. Feel free to re-open if the problem still not resolved. Thank you!
