### ISSUE TITLE
test.sh: peer-cli-assist command does not exist in '/project/src/github.com/hyperledger/fabric-private-chaincode/utils/fabric'

### ISSUE THREAD

**Issue by Sh4d0wBlade** [hyperledger/fabric-private-chaincode#673]
Hi, I'm a new guy to FPC and when I followed the hello world example for getting started, I successfully build and make the helloworld_cc.cpp but a command ". ${FABRIC_SCRIPTDIR}/lib/common_ledger.sh" in the tesh.sh file reported that "peer-cli-assist command does not exist in '/project/src/github.com/hyperledger/fabric-private-chaincode/utils/fabric". Don't know what to do to fix this. Would you guys please tell me how to solve this? I used  "Option 1: Using the Docker-based FPC Development Environment" to deploy the Hello World Tutorial

**Comment by mbrandenburger** [comment]
Hi @Sh4d0wBlade, did you run a `make` or `make build` in `$FPC_PATH`?

**Comment by mbrandenburger** [comment]
Closing for now - please reopen if you still fight with this issue. Thanks!
