### ISSUE TITLE
Failed to connect to 127.0.0.1 port 8080: Connection refused

### ISSUE THREAD

**Issue by knight-hjh** [hyperledger/fabric-private-chaincode#679]
when I use the command make run-dev It reports the error. 
![image](https://user-images.githubusercontent.com/38315608/177280318-e6bd2583-eaea-41a4-8902-cbe67dd05eaf.png)
anyone knows how to solve it. :(

**Comment by mbrandenburger** [comment]
Hi @knight-hjh, are you sitting behind some proxy? It seems it tries to connect to your localhost (127.0.0.1:8080) in oder to checkout the fabric github repo.

**Comment by knight-hjh** [comment]
yeah. but the proxy is set to 127.0.0.1:58591

**Comment by knight-hjh** [comment]
I remove the proxy and rerun the command. but it report:
![image](https://user-images.githubusercontent.com/38315608/177302910-b4233cf4-0844-445e-bfcc-17c6ba5163d4.png)
Is that right?

**Comment by knight-hjh** [comment]
Thanks, it works now. 
By the way. 
![image](https://user-images.githubusercontent.com/38315608/177347945-da6c1055-66f0-47ec-85e4-f521c411ecc0.png)
I have read the related issues. But still don't know how to fix it. The version of open-ssl is right.
Do you have any idea?

**Comment by mbrandenburger** [comment]
Let me first close this issue as it was resolved. The other you have related to openssl we can discuss on discord.
