### ISSUE TITLE
Docker commands are not found inside the development environment 

### ISSUE THREAD

**Issue by munapower** [hyperledger/fabric-private-chaincode#715]
**Describe the bug**

Once Docker environment is updated to 4.21.x you can start the development environment but if you try to run the `make build` command you get the following message `Cannot connect to the Docker daemon at unix:///Users/XXX/.docker/run/docker.sock. Is the docker daemon running?`

**To Reproduce**

1- Start dev environment with `make -C utils/docker build build-dev run-dev`
2- from inside the container run `make build` and at one point you will get the following:
```
FABRIC_IMAGES: peer orderer ccenv tools baseos
===> Pulling fabric Images
====>  docker.io/hyperledger/fabric-peer:2.5.3
Cannot connect to the Docker daemon at unix:///Users/XXX.docker/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///Users/XXX/.docker/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///Users/XXX/.docker/run/docker.sock. Is the docker daemon running?
```

**Expected behavior**

User should be able to run the make build and the container find the docker commands.
**Log-filesScreenshots**

**Environment (please complete the following information):**

- Mac OS 13.5
- FPC: main github branch
- Docker for Desktop: 4.21.1
**Additional context**

I had added the docker_host in the config override but it didn't use it
I saw it listed with docker context
```
docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                     KUBERNETES ENDPOINT   ORCHESTRATOR
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock
desktop-linux *     moby                Docker Desktop                            unix:///Users/XXX/.docker/run/docker.sock
```
UNTIL I ran `docker context use default` and voila, the `make clean `inside the container did a lot more than it had previously
and the `make build` worked!

**Comment by munapower** [comment]
Not sure if this could be a solution https://docs.docker.com/desktop/extensions-sdk/guides/use-docker-socket-from-backend/

**Comment by munapower** [comment]
Ah, yes, here it says that the context is desktop-linux https://docs.docker.com/desktop/mac/permission-requirements/#installing-symlinks

**Comment by mbrandenburger** [comment]
Using rancher-desktop 1.9.1 has the same issue with the docker context. When running `docker context use default` inside the FPC dev container, I can successfully use docker.

**Comment by munapower** [comment]
@mbrandenburger Yes I was going to otherwise propose amend the readme and tell people what to do there. I can try this and see what happens.
