### ISSUE TITLE
Problem of Build Fabric Private Chaincode

### ISSUE THREAD

**Issue by liuchao11** [hyperledger/fabric-private-chaincode#716]
When I build FPC as [Build Fabric Private Chaincode](https://github.com/hyperledger/fabric-private-chaincode#build-fabric-private-chaincode).  "Make docker" is no problem. When I tap make, the problem is as follow:
make[1]: Leaving directory '/project/src/github.com/hyperledger/fabric-private-chaincode/utils'
make[1]: Entering directory '/project/src/github.com/hyperledger/fabric-private-chaincode/integration'
./auction_test.sh
**auction_test.sh: FABRIC_BIN_DIR not properly defined as '/project/src/github.com/hyperledger/fabric-private-chaincode/fabric/_internal/bin'**
make[1]: *** [Makefile:13: auction_test] Error 111
make[1]: Leaving directory '/project/src/github.com/hyperledger/fabric-private-chaincode/integration'
make: *** [Makefile:22: test] Error 2

Another problem is as below:

ERROR  (/project/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/pdo-crypto-c-wrapper.cpp:62) error at /project/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/pdo-crypto-c-wrapper.cpp:62: Crypto Error (deserializeECDSAPublicKey): Could not deserialize public ECDSA key

ERROR  (/project/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/pdo-crypto-c-wrapper.cpp:130) error at /project/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/pdo-crypto-c-wrapper.cpp:130: Crypto Error (deserializeRSAPublicKey): Could not deserialize public RSA key

ERROR  (/project/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/pdo-crypto-c-wrapper.cpp:166) error at /project/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/pdo-crypto-c-wrapper.cpp:166: Crypto Error (deserializeRSAPrivateKey): Could not deserialize private RSA key

ERROR  (/project/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/pdo-crypto-c-wrapper.cpp:199) error at /project/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/pdo-crypto-c-wrapper.cpp:199: Crypto Error (EncryptMessage): Wrong AES-GCM key length

ERROR  (/project/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/pdo-crypto-c-wrapper.cpp:232) error at /project/src/github.com/hyperledger/fabric-private-chaincode/common/crypto/pdo-crypto-c-wrapper.cpp:232: Crypto Error (DecryptMessage): Wrong AES-GCM key length

**Expected behavior**

  How can solve the problems?

**Comment by mbrandenburger** [comment]
Hi!
> make[1]: Leaving directory '/project/src/github.com/hyperledger/fabric-private-chaincode/utils'
make[1]: Entering directory '/project/src/github.com/hyperledger/fabric-private-chaincode/integration'
./auction_test.sh
auction_test.sh: FABRIC_BIN_DIR not properly defined as '/project/src/github.com/hyperledger/fabric-private-chaincode/fabric/_internal/bin'
make[1]: *** [Makefile:13: auction_test] Error 111
make[1]: Leaving directory '/project/src/github.com/hyperledger/fabric-private-chaincode/integration'
make: *** [Makefile:22: test] Error 2

`FABRIC_BIN_DIR` should be set via the `config.mk`. Please check that `$FPC_PATH/fabric/_internal/bin` exists. It should be downloaded automatically when running `make`. I suggest that you run `make clean` to tidy up your environment. Then `make build` to just build all the FPC components and see that this works. Finally, run `make test`.


For the other error related to the `common/crypto` package I am missing a bit of context. I could be that this fails as other tests already have failed?!

**Comment by liuchao11** [comment]
> Hi!
> 
> > make[1]: Leaving directory '/project/src/github.com/hyperledger/fabric-private-chaincode/utils'
> > make[1]: Entering directory '/project/src/github.com/hyperledger/fabric-private-chaincode/integration'
> > ./auction_test.sh
> > auction_test.sh: FABRIC_BIN_DIR not properly defined as '/project/src/github.com/hyperledger/fabric-private-chaincode/fabric/_internal/bin'
> > make[1]: *** [Makefile:13: auction_test] Error 111
> > make[1]: Leaving directory '/project/src/github.com/hyperledger/fabric-private-chaincode/integration'
> > make: *** [Makefile:22: test] Error 2
> 
> `FABRIC_BIN_DIR` should be set via the `config.mk`. Please check that `$FPC_PATH/fabric/_internal/bin` exists. It should be downloaded automatically when running `make`. I suggest that you run `make clean` to tidy up your environment. Then `make build` to just build all the FPC components and see that this works. Finally, run `make test`.
> 
> For the other error related to the `common/crypto` package I am missing a bit of context. I could be that this fails as other tests already have failed?

**Comment by liuchao11** [comment]
> > Hi!
> > > make[1]: Leaving directory '/project/src/github.com/hyperledger/fabric-private-chaincode/utils'
> > > make[1]: Entering directory '/project/src/github.com/hyperledger/fabric-private-chaincode/integration'
> > > ./auction_test.sh
> > > auction_test.sh: FABRIC_BIN_DIR not properly defined as '/project/src/github.com/hyperledger/fabric-private-chaincode/fabric/_internal/bin'
> > > make[1]: *** [Makefile:13: auction_test] Error 111
> > > make[1]: Leaving directory '/project/src/github.com/hyperledger/fabric-private-chaincode/integration'
> > > make: *** [Makefile:22: test] Error 2
> > 
> > 
> > `FABRIC_BIN_DIR` should be set via the `config.mk`. Please check that `$FPC_PATH/fabric/_internal/bin` exists. It should be downloaded automatically when running `make`. I suggest that you run `make clean` to tidy up your environment. Then `make build` to just build all the FPC components and see that this works. Finally, run `make test`.
> > For the other error related to the `common/crypto` package I am missing a bit of context. I could be that this fails as other tests already have failed?

I just remove all containers and repeat the building progrecess. The problem are still there. There is no $FPC_PATH/fabric/_internal/bin exists. How can solve the problems?

**Comment by mbrandenburger** [comment]
Do you use the FPC docker dev container?

You can run `make -C $FPC_PATH/fabric`. That should download the binaries into `fabric/_internal/bin`
