### ISSUE TITLE
CI CD build error

### ISSUE THREAD

**Issue by chenchanglew** [hyperledger/fabric-private-chaincode#746]
**Describe the bug**
In CI/CD, step run make inside dev container, it will failed shows as follow
```
mkdir -p _internal && cd _internal \
&& curl -sSL https://bit.ly/2ysbOFE | bash -s -- 2.5.4 1.5.7 -s \
&& touch .fetched
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE html>'
```
This is because the link  https://bit.ly/2ysbOFE has been considered as harmful link in billy.
thus we will need to just use the original link: https://raw.githubusercontent.com/hyperledger/fabric/master/scripts/bootstrap.sh to install

**To Reproduce**
create a PR and it will failed in the step of 

**Expected behavior**

**Log-filesScreenshots**
https://bit.ly/2ysbOFE

**Environment (please complete the following information):**
GITHUB

**Comment by bvavala** [comment]
It looks accurate, I am ok with the change.

**Comment by mbrandenburger** [comment]
Looks good to me. @chenchanglew do you want to create a PR that changes the url in the curl command?

**Comment by mbrandenburger** [comment]
It seems that the bit.ly link works again

**Comment by mbrandenburger** [comment]
Closing as this is not an issue anymore. We can reopen if the problem comes back.
